// src/components/common/CountryFlag.tsx

import React, { useState } from 'react';

// Comprehensive FIDE 3-letter IOC/FIDE federation code to ISO 3166-1 alpha-2 mapping
const FIDE_TO_ISO2: Record<string, string> = {
  // North America
  USA: 'us',
  CAN: 'ca',
  MEX: 'mx',
  CUB: 'cu',
  JAM: 'jm',
  BAR: 'bb',
  BER: 'bm',
  BAH: 'bs',
  TTO: 'tt',
  HAI: 'ht',
  DOM: 'do',
  PUR: 'pr',
  CRC: 'cr',
  PAN: 'pa',
  NCA: 'ni',
  HON: 'hn',
  ESA: 'sv',
  GUA: 'gt',
  BIZ: 'bz',
  ARU: 'aw',
  AHO: 'cw',
  CUW: 'cw',
  LCA: 'lc',
  SKN: 'kn',
  VIN: 'vc',
  ANT: 'ag',
  DMA: 'dm',
  GRN: 'gd',
  ISV: 'vi',
  IVB: 'vg',
  CAY: 'ky',

  // Asia & Oceania
  IND: 'in',
  CHN: 'cn',
  UZB: 'uz',
  JPN: 'jp',
  KOR: 'kr',
  VIE: 'vn',
  PHI: 'ph',
  INA: 'id',
  SGP: 'sg',
  MAS: 'my',
  MGL: 'mn',
  KAZ: 'kz',
  KGZ: 'kg',
  TJK: 'tj',
  TKM: 'tm',
  BAN: 'bd',
  SRI: 'lk',
  PAK: 'pk',
  NEP: 'np',
  BHU: 'bt',
  MDV: 'mv',
  AFG: 'af',
  MYA: 'mm',
  CAM: 'kh',
  LAO: 'la',
  BRU: 'bn',
  THA: 'th',
  AUS: 'au',
  NZL: 'nz',
  FIJ: 'fj',
  PNG: 'pg',
  GUM: 'gu',
  SOL: 'sb',
  PLW: 'pw',
  VAN: 'vu',
  IRI: 'ir',
  IRQ: 'iq',
  UAE: 'ae',
  QAT: 'qa',
  KUW: 'kw',
  BRN: 'bh',
  OMA: 'om',
  YEM: 'ye',
  KSA: 'sa',
  JOR: 'jo',
  LBN: 'lb',
  SYR: 'sy',
  PLE: 'ps',
  ISR: 'il',
  TUR: 'tr',
  HKG: 'hk',
  MAC: 'mo',
  TPE: 'tw',

  // Europe
  NOR: 'no',
  FRA: 'fr',
  GER: 'de',
  ESP: 'es',
  NED: 'nl',
  ENG: 'gb',
  SCO: 'gb',
  WLS: 'gb',
  IRL: 'ie',
  POL: 'pl',
  AZE: 'az',
  ARM: 'am',
  UKR: 'ua',
  GEO: 'ge',
  HUN: 'hu',
  ROU: 'ro',
  CZE: 'cz',
  ITA: 'it',
  SWE: 'se',
  DEN: 'dk',
  FIN: 'fi',
  ISL: 'is',
  FAI: 'fo', // Faroe Islands
  FRO: 'fo',
  GRE: 'gr',
  CRO: 'hr',
  SRB: 'rs',
  SLO: 'si',
  SVK: 'sk',
  AUT: 'at',
  SUI: 'ch',
  BEL: 'be',
  POR: 'pt',
  LTU: 'lt',
  LAT: 'lv',
  EST: 'ee',
  MDA: 'md',
  BLR: 'by',
  MNE: 'me',
  MKD: 'mk',
  BIH: 'ba',
  BUL: 'bg',
  ALB: 'al',
  KOS: 'xk',
  CYP: 'cy',
  MLT: 'mt', // Malta
  MNC: 'mc', // Monaco
  AND: 'ad',
  SMR: 'sm',
  LIE: 'li',
  LUX: 'lu',
  JCI: 'je',
  GCI: 'gg',
  IOM: 'im',
  RUS: 'ru',
  FID: 'un', // International FIDE neutral flag
  FIDE: 'un',

  // South America
  BRA: 'br',
  ARG: 'ar',
  CHI: 'cl',
  COL: 'co',
  PER: 'pe',
  URU: 'uy',
  PAR: 'py',
  VEN: 've',
  ECU: 'ec',
  BOL: 'bo',
  GUY: 'gy',
  SUR: 'sr',

  // Africa
  EGY: 'eg',
  RSA: 'za',
  ALG: 'dz',
  MAR: 'ma',
  TUN: 'tn',
  LBA: 'ly',
  SUD: 'sd',
  SSD: 'ss',
  ETH: 'et',
  ERI: 'er',
  DJI: 'dj',
  SOM: 'so',
  KEN: 'ke',
  TAN: 'tz',
  UGA: 'ug',
  RWA: 'rw',
  BDI: 'bi',
  NGR: 'ng',
  GHA: 'gh',
  CIV: 'ci',
  SEN: 'sn',
  CMR: 'cm',
  ZAM: 'zm',
  ZIM: 'zw',
  ANG: 'ao',
  MOZ: 'mz',
  NAM: 'na',
  BOT: 'bw',
  MAW: 'mw',
  LES: 'ls',
  SWZ: 'sz',
  MAD: 'mg',
  MRI: 'mu',
  SEY: 'sc',
};

// Full English & Olympiad country/team name to ISO 3166-1 alpha-2 mapping
const COUNTRY_NAME_TO_ISO2: Record<string, string> = {
  // Common Olympiad & Tournament Team Names
  'UNITED STATES OF AMERICA': 'us',
  'UNITED STATES': 'us',
  USA: 'us',
  AMERICA: 'us',
  HUNGARY: 'hu',
  MALTA: 'mt',
  JAMAICA: 'jm',
  UZBEKISTAN: 'uz',
  IRAQ: 'iq',
  INDIA: 'in',
  THAILAND: 'th',
  CHINA: 'cn',
  UGANDA: 'ug',
  'FAROE ISLANDS': 'fo',
  GERMANY: 'de',
  NETHERLANDS: 'nl',
  'HONG KONG, CHINA': 'hk',
  'HONG KONG': 'hk',
  MOROCCO: 'ma',
  AZERBAIJAN: 'az',
  TUNISIA: 'tn',
  FRANCE: 'fr',
  ARMENIA: 'am',
  BARBADOS: 'bb',
  MONACO: 'mc',
  ENGLAND: 'gb',
  'GREAT BRITAIN': 'gb',
  'UNITED KINGDOM': 'gb',
  SCOTLAND: 'gb',
  WALES: 'gb',
  UKRAINE: 'ua',
  ZIMBABWE: 'zw',
  NORWAY: 'no',
  SPAIN: 'es',
  POLAND: 'pl',
  ROMANIA: 'ro',
  'CZECH REPUBLIC': 'cz',
  CZECHIA: 'cz',
  ITALY: 'it',
  SWEDEN: 'se',
  DENMARK: 'dk',
  FINLAND: 'fi',
  ICELAND: 'is',
  GREECE: 'gr',
  CROATIA: 'hr',
  SERBIA: 'rs',
  SLOVENIA: 'si',
  SLOVAKIA: 'sk',
  AUSTRIA: 'at',
  SWITZERLAND: 'ch',
  BELGIUM: 'be',
  PORTUGAL: 'pt',
  IRELAND: 'ie',
  RUSSIA: 'ru',
  BRAZIL: 'br',
  ARGENTINA: 'ar',
  CHILE: 'cl',
  COLOMBIA: 'co',
  PERU: 'pe',
  EGYPT: 'eg',
  'SOUTH AFRICA': 'za',
  TURKEY: 'tr',
  TÜRKIYE: 'tr',
  IRAN: 'ir',
  'IRAN, ISLAMIC REPUBLIC OF': 'ir',
  ISRAEL: 'il',
  CANADA: 'ca',
  AUSTRALIA: 'au',
  VIETNAM: 'vn',
  'VIET NAM': 'vn',
  PHILIPPINES: 'ph',
  INDONESIA: 'id',
  SINGAPORE: 'sg',
  KAZAKHSTAN: 'kz',
  MONGOLIA: 'mn',
  JAPAN: 'jp',
  'SOUTH KOREA': 'kr',
  'KOREA, SOUTH': 'kr',
  KOREA: 'kr',
  'NORTH MACEDONIA': 'mk',
  MACEDONIA: 'mk',
  'BOSNIA AND HERZEGOVINA': 'ba',
  'BOSNIA & HERZEGOVINA': 'ba',
  BOSNIA: 'ba',
  MONTENEGRO: 'me',
  ALBANIA: 'al',
  KOSOVO: 'xk',
  CYPRUS: 'cy',
  ESTONIA: 'ee',
  LATVIA: 'lv',
  LITHUANIA: 'lt',
  MOLDOVA: 'md',
  'MOLDOVA, REPUBLIC OF': 'md',
  BELARUS: 'by',
  GEORGIA: 'ge',
  TAJIKISTAN: 'tj',
  TURKMENISTAN: 'tm',
  KYRGYZSTAN: 'kg',
  BANGLADESH: 'bd',
  'SRI LANKA': 'lk',
  PAKISTAN: 'pk',
  NEPAL: 'np',
  BHUTAN: 'bt',
  MALDIVES: 'mv',
  AFGHANISTAN: 'af',
  MYANMAR: 'mm',
  CAMBODIA: 'kh',
  LAOS: 'la',
  MALAYSIA: 'my',
  BRUNEI: 'bn',
  TAIWAN: 'tw',
  'CHINESE TAIPEI': 'tw',
  'NEW ZEALAND': 'nz',
  FIJI: 'fj',
  'PAPUA NEW GUINEA': 'pg',
  GUAM: 'gu',
  'SAUDI ARABIA': 'sa',
  'UNITED ARAB EMIRATES': 'ae',
  UAE: 'ae',
  QATAR: 'qa',
  KUWAIT: 'kw',
  BAHRAIN: 'bh',
  OMAN: 'om',
  YEMEN: 'ye',
  JORDAN: 'jo',
  LEBANON: 'lb',
  SYRIA: 'sy',
  PALESTINE: 'ps',
  ALGERIA: 'dz',
  LIBYA: 'ly',
  SUDAN: 'sd',
  'SOUTH SUDAN': 'ss',
  ETHIOPIA: 'et',
  ERITREA: 'er',
  DJIBOUTI: 'dj',
  SOMALIA: 'so',
  KENYA: 'ke',
  TANZANIA: 'tz',
  RWANDA: 'rw',
  BURUNDI: 'bi',
  NIGERIA: 'ng',
  GHANA: 'gh',
  'IVORY COAST': 'ci',
  "COTE D'IVOIRE": 'ci',
  "CÔTE D'IVOIRE": 'ci',
  SENEGAL: 'sn',
  CAMEROON: 'cm',
  ZAMBIA: 'zm',
  ANGOLA: 'ao',
  MOZAMBIQUE: 'mz',
  NAMIBIA: 'na',
  BOTSWANA: 'bw',
  MALAWI: 'mw',
  LESOTHO: 'ls',
  ESWATINI: 'sz',
  SWAZILAND: 'sz',
  MADAGASCAR: 'mg',
  MAURITIUS: 'mu',
  SEYCHELLES: 'sc',
  MEXICO: 'mx',
  CUBA: 'cu',
  'DOMINICAN REPUBLIC': 'do',
  HAITI: 'ht',
  'PUERTO RICO': 'pr',
  'TRINIDAD AND TOBAGO': 'tt',
  BAHAMAS: 'bs',
  GUYANA: 'gy',
  SURINAME: 'sr',
  VENEZUELA: 've',
  BOLIVIA: 'bo',
  ECUADOR: 'ec',
  PARAGUAY: 'py',
  URUGUAY: 'uy',
  'COSTA RICA': 'cr',
  PANAMA: 'pa',
  NICARAGUA: 'ni',
  HONDURAS: 'hn',
  'EL SALVADOR': 'sv',
  GUATEMALA: 'gt',
  BELIZE: 'bz',
  BERMUDA: 'bm',
  'CAYMAN ISLANDS': 'ky',
  ARUBA: 'aw',
  CURACAO: 'cw',
  'SAINT LUCIA': 'lc',
  'ST. LUCIA': 'lc',
  'SAINT KITTS AND NEVIS': 'kn',
  'SAINT VINCENT AND THE GRENADINES': 'vc',
  'ANTIGUA AND BARBUDA': 'ag',
  DOMINICA: 'dm',
  GRENADA: 'gd',
  ANDORRA: 'ad',
  'SAN MARINO': 'sm',
  LIECHTENSTEIN: 'li',
  LUXEMBOURG: 'lu',
  JERSEY: 'je',
  GUERNSEY: 'gg',
  'ISLE OF MAN': 'im',
};

// Extended dictionary for top Grandmasters & players when PGN metadata is stripped
const PLAYER_COUNTRY_FALLBACK: Record<string, string> = {
  // Top Classical / Rapid GMs
  carlsen: 'no',
  nakamura: 'us',
  caruana: 'us',
  gukesh: 'in',
  praggnanandhaa: 'in',
  erigaisi: 'in',
  anand: 'in',
  ding: 'cn',
  firouzja: 'fr',
  nepomniachtchi: 'ru',
  giri: 'nl',
  abdusattorov: 'uz',
  so: 'us',
  aronian: 'us',
  keymer: 'de',
  rapport: 'hu',
  'vachier-lagrave': 'fr',
  duda: 'pl',
  mamedyarov: 'az',
  radjabov: 'az',
  vidit: 'in',
  'wei yi': 'cn',
  maghsoodloo: 'ir',
  tabatabaei: 'ir',
  niemann: 'us',
  sevian: 'us',
  shankland: 'us',
  robson: 'us',
  dominguez: 'us',
  mishra: 'us',
  xiong: 'us',
  liang: 'us',
  yoo: 'us',
  woodward: 'us',
  sarin: 'in',
  sadhwani: 'in',
  mendonca: 'in',
  harikrishna: 'in',
  karthikeyan: 'in',
  aravindh: 'in',
  adhiban: 'in',
  sethuraman: 'in',
  'yu yangyi': 'cn',
  'wang hao': 'cn',
  'bu xiangzhi': 'cn',
  'ni hua': 'cn',
  'lu shanglei': 'cn',
  sindarov: 'uz',
  vokhidov: 'uz',
  yakubboev: 'uz',
  kasimdzhanov: 'uz',
  sarana: 'rs',
  fedoseev: 'si',
  deac: 'ro',
  shevchenko: 'ro',
  'van foreest': 'nl',
  bok: 'nl',
  bluebaum: 'de',
  blübaum: 'de',
  kollars: 'de',
  svane: 'de',
  donchenko: 'de',
  nisipeanu: 'de',
  bacrot: 'fr',
  fressinet: 'fr',
  cornette: 'fr',
  bauer: 'fr',
  maurizzi: 'fr',
  navara: 'cz',
  nguyen: 'cz',
  pechac: 'cz',
  bjerre: 'dk',
  christiansen: 'no',
  tari: 'no',
  hammer: 'no',
  urkedal: 'no',
  grandelius: 'se',
  vallejo: 'es',
  shirov: 'es',
  antón: 'es',
  anton: 'es',
  korobov: 'ua',
  ivanchuk: 'ua',
  ponomariov: 'ua',
  volokitin: 'ua',
  howell: 'gb',
  jones: 'gb',
  mcshane: 'gb',
  adams: 'gb',
  short: 'gb',
  yilmaz: 'tr',
  sanal: 'tr',
  can: 'tr',
  idani: 'ir',
  daneshvar: 'ir',
  sonnleitner: 'at',
  leko: 'hu',
  gledura: 'hu',
  banusz: 'hu',
  dudin: 'hu',

  // Top Women
  vaishali: 'in',
  humpy: 'in',
  harika: 'in',
  'ju wenjun': 'cn',
  'lei tingjie': 'cn',
  'tan zhongyi': 'cn',
  'hou yifan': 'cn',
  goryachkina: 'ru',
  lagno: 'ru',
  kosteniuk: 'ch',
  muzychuk: 'ua',
  salimova: 'bg',
  assaubayeva: 'kz',
  paehtz: 'de',
  päähtz: 'de',
  stefanova: 'bg',
  cramling: 'se',
  bodnaruk: 'ru',
};

export function resolveIsoCountry(
  fed?: string | null,
  playerName?: string | null
): string | null {
  // 1. Direct FIDE / ISO / Country name lookup
  if (fed) {
    let clean = fed.trim().toUpperCase().replace(/[\(\)\[\]]/g, '');
    // Strip trailing team suffixes like " 1", " 2", " B", " C", " (OPEN)", " WOMEN", " MEN"
    clean = clean.replace(/\s+(?:[0-9]|B|C|OPEN|WOMEN|MEN|TEAM)\s*$/i, '').trim();

    if (FIDE_TO_ISO2[clean]) return FIDE_TO_ISO2[clean];
    if (COUNTRY_NAME_TO_ISO2[clean]) return COUNTRY_NAME_TO_ISO2[clean];
    if (/^[A-Z]{2}$/.test(clean)) return clean.toLowerCase();

    // Partial / Substring Match for complex team names (e.g. "Hong Kong, China", "United States of America")
    for (const [name, iso] of Object.entries(COUNTRY_NAME_TO_ISO2)) {
      if (clean === name || clean.startsWith(name) || name.startsWith(clean)) {
        return iso;
      }
    }
  }

  // 2. Extract country/fed bracketed in player name: e.g. "Sonnleitner, Laura (AUT)" or "[USA]" or "/GER/"
  if (playerName) {
    const match = playerName.match(/[\(\[\/]([A-Za-z\s,]{2,25})[\)\]\/]/);
    if (match) {
      const code = match[1].trim().toUpperCase();
      if (FIDE_TO_ISO2[code]) return FIDE_TO_ISO2[code];
      if (COUNTRY_NAME_TO_ISO2[code]) return COUNTRY_NAME_TO_ISO2[code];
      if (/^[A-Z]{2}$/.test(code)) return code.toLowerCase();
    }
  }

  // 3. Fallback to Grandmaster / Player dictionary
  if (playerName) {
    const lowerName = playerName.toLowerCase();
    for (const [key, iso] of Object.entries(PLAYER_COUNTRY_FALLBACK)) {
      if (lowerName.includes(key)) {
        return iso;
      }
    }
  }

  return null;
}

interface CountryFlagProps {
  countryCode?: string | null;
  playerName?: string | null;
  className?: string;
}

export const CountryFlag: React.FC<CountryFlagProps> = ({
  countryCode,
  playerName,
  className = '',
}) => {
  const [imgError, setImgError] = useState(false);
  const iso2 = resolveIsoCountry(countryCode, playerName);

  if (!iso2) return null;

  if (imgError) {
    return (
      <span
        className={`inline-flex items-center text-[9px] font-mono font-bold text-stone-400 bg-[#181c26] px-1 py-0.5 rounded border border-stone-700/70 shrink-0 ${className}`}
        title={countryCode?.toUpperCase() || iso2.toUpperCase()}
      >
        {iso2.toUpperCase()}
      </span>
    );
  }

  return (
    <span
      className={`inline-flex items-center shrink-0 ${className}`}
      title={countryCode?.toUpperCase() || iso2.toUpperCase()}
    >
      <img
        src={`https://flagcdn.com/w40/${iso2}.png`}
        srcSet={`https://flagcdn.com/w80/${iso2}.png 2x`}
        alt={iso2.toUpperCase()}
        className="w-[18px] h-[13px] object-cover rounded-[2px] shadow-sm border border-stone-700/60 transition-transform hover:scale-110"
        loading="lazy"
        onError={() => setImgError(true)}
      />
    </span>
  );
};
